// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P9_Blog_Generator_AI_Backend.Data;

#nullable disable

namespace P9_Blog_Generator_AI_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P9_Blog_Generator_AI_Backend.Models.BlogRequest", b =>
                {
                    b.Property<int>("BlogRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogRequestId"));

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("BlogRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("BlogRequests");
                });

            modelBuilder.Entity("P9_Blog_Generator_AI_Backend.Models.GeneratedBlog", b =>
                {
                    b.Property<int>("GeneratedBlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneratedBlogId"));

                    b.Property<int>("BlogRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeneratedBlogId");

                    b.HasIndex("BlogRequestId");

                    b.ToTable("GeneratedBlogs");
                });

            modelBuilder.Entity("P9_Blog_Generator_AI_Backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("P9_Blog_Generator_AI_Backend.Models.BlogRequest", b =>
                {
                    b.HasOne("P9_Blog_Generator_AI_Backend.Models.User", "User")
                        .WithMany("BlogRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("P9_Blog_Generator_AI_Backend.Models.GeneratedBlog", b =>
                {
                    b.HasOne("P9_Blog_Generator_AI_Backend.Models.BlogRequest", "BlogRequest")
                        .WithMany("GeneratedBlogs")
                        .HasForeignKey("BlogRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogRequest");
                });

            modelBuilder.Entity("P9_Blog_Generator_AI_Backend.Models.BlogRequest", b =>
                {
                    b.Navigation("GeneratedBlogs");
                });

            modelBuilder.Entity("P9_Blog_Generator_AI_Backend.Models.User", b =>
                {
                    b.Navigation("BlogRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
